### ISSUE TITLE
tensorflow, keras を使用時のメモリについての調査

### ISSUE THREAD

**Issue by yonedahayato** [yonedahayato/stock_strategy#29]
# 検索
- keras memory 解放
- keras メモリ 解放
- keras memory release
- tensorflow memory 解放
- tensorflow メモリ 解放

# 調査
- [Kerasでメモリ使用量を減らしたかったらmax_queue_sizeを調整しよう](https://blog.shikoan.com/keras_max_queue/)
- [How could I release gpu memory of keras](https://forums.fast.ai/t/how-could-i-release-gpu-memory-of-keras/2023)

# 検証
- [x] git push
- [x] インスタンス作成
- [x] git fetch , rebase
- [x] swap 追加(2M)
- [x] 検証
- [x] 後片付け
  - [x] log 回収
    - [log file](https://drive.google.com/open?id=1H73KcEL0_2VIELHHtNZS-XBrRMLt3GDL)
  - [x] スナップショット作成
  - [x] インスタンス削除
- [x] error log 確認
  - 結果銘柄0件
  - permission のため結果ファイルを作成 or 生成 できなかった

# 結果
- 最後まで動いていそう？
- いくつかエラーが発生していたので、それを確認しましょう

**Comment by yonedahayato** [comment]
# error log 
```
[I 190626 23:06:28 stock_strategy:197] [Stock_Storategy:exect]: code 9501, 221 / 225
[E 190626 23:06:28 stock_strategy:203] [Stock_Storategy:exect]: fail to get stock histlical data.
[E 190626 23:06:28 stock_strategy:204] [Stock_Storategy:exect]: fail to get stock histlical data.
    Traceback (most recent call last):
      File "/home/yhayato1320/stock_strategy/stock_strategy/stock_strategy.py", line 200, in execute
        stock_data_df = self.get_stock_data(code)
      File "/home/yhayato1320/stock_strategy/stock_strategy/stock_strategy.py", line 88, in get_stock_data
        stock_data_df = pd.read_csv(HISTRICAL_DATA_PATH.format(code=code), index_col=0)
      File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 655, in parser_f
        return _read(filepath_or_buffer, kwds)
      File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 405, in _read
        parser = TextFileReader(filepath_or_buffer, **kwds)
      File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 764, in __init__
        self._make_engine(self.engine)
      File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 985, in _make_engine
        self._engine = CParserWrapper(self.f, **self.options)
      File "/usr/local/lib/python3.5/dist-packages/pandas/io/parsers.py", line 1605, in __init__
        self._reader = parsers.TextReader(src, **kwds)
      File "pandas/_libs/parsers.pyx", line 394, in pandas._libs.parsers.TextReader.__cinit__ (pandas/_libs/parsers.c:4209)
      File "pandas/_libs/parsers.pyx", line 710, in pandas._libs.parsers.TextReader._setup_parser_source (pandas/_libs/parsers.c:8873)
    FileNotFoundError: File b'/home/yhayato1320/stock_strategy/get_stock_info/stock_data/9501.csv' does not exist
```

**Comment by yonedahayato** [comment]
# log
```
[I 190626 23:06:28 stock_strategy:137] [Stock_Storategy:check_select_code]: []
[I 190626 23:06:28 stock_strategy:241] [Stock_Storategy:exect]: success to check select code.
[I 190626 23:06:28 save_result:20] [Save_Result:__init__]: save_path: /home/yhayato1320/stock_strategy/check_reward/result/selected_code
[E 190626 23:06:28 save_result:61] [Save_Result:save]: failt to save to json, format: {'creat_time': '2019_06_26_23_06_28', 'data_range_start_to_compute': '2010-01-04', 'data_range_end_to_compute': '2019-03-08', 'back_test_return_date': 0, 'method': 'predict_class_of_change_using_lstm', 'elapsed_time_average': 149.2470180627403, 'result_code_list': []}, [Errno 13] Permission denied: '/home/yhayato1320/stock_strategy/check_reward/result/selected_code/predict_class_of_change_using_lstm_2019_06_26_23_06_28.json'
[E 190626 23:06:28 save_result:62] failt to save to json, format: {'creat_time': '2019_06_26_23_06_28', 'data_range_start_to_compute': '2010-01-04', 'data_range_end_to_compute': '2019-03-08', 'back_test_return_date': 0, 'method': 'predict_class_of_change_using_lstm', 'elapsed_time_average': 149.2470180627403, 'result_code_list': []}, [Errno 13] Permission denied: '/home/yhayato1320/stock_strategy/check_reward/result/selected_code/predict_class_of_change_using_lstm_2019_06_26_23_06_28.json'
    Traceback (most recent call last):
      File "/home/yhayato1320/stock_strategy/check_reward/save_result.py", line 54, in save
        with open(file_path, "w") as file:
    PermissionError: [Errno 13] Permission denied: '/home/yhayato1320/stock_strategy/check_reward/result/selected_code/predict_class_of_change_using_lstm_2019_06_26_23_06_28.json'
[E 190626 23:06:28 stock_strategy:248] [Stock_Storategy:exect]: fail to save result select code.
[E 190626 23:06:28 stock_strategy:249] [Stock_Storategy:exect]: fail to save result select code.
    Traceback (most recent call last):
      File "/home/yhayato1320/stock_strategy/check_reward/save_result.py", line 54, in save
        with open(file_path, "w") as file:
    PermissionError: [Errno 13] Permission denied: '/home/yhayato1320/stock_strategy/check_reward/result/selected_code/predict_class_of_change_using_lstm_2019_06_26_23_06_28.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/yhayato1320/stock_strategy/stock_strategy/stock_strategy.py", line 244, in execute
        json_result = self.save_result()
      File "/home/yhayato1320/stock_strategy/stock_strategy/stock_strategy.py", line 132, in save_result
        json_result = sr.save()
      File "/home/yhayato1320/stock_strategy/check_reward/save_result.py", line 63, in save
        raise Exception(e)
    Exception: [Errno 13] Permission denied: '/home/yhayato1320/stock_strategy/check_reward/result/selected_code/predict_class_of_change_using_lstm_2019_06_26_23_06_28.json'
```

**Comment by yonedahayato** [comment]
- #34にタスクを引き継いでいるステータス
